# vim:sw=2:ts=2:sts=2:et

name: 'CD action for building jekyll site'

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      -
        name: Setup Ruby and dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
      -
        name: Building site using jekyll
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll b -d "_site" --config "_config.yml"
      -
        name: Validate HTML using html-proofer
        run: |
          bundle exec htmlproofer \
            --allow_hash_href --disable_external --check_html "_site"
      -
        name: Upload artifact of build result
        uses: actions/upload-artifact@v2
        with:
          name: supershadoe_io-pages
          path: _site
          retention-days: 1
  deploy-site-to-gh-pages:
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      -
        name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: gh-pages
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: supershadoe_io-pages
      -
        name: List files after unpacking
        run: ls -a
      -
        name: Push to origin/gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"
          git update-ref -d HEAD
          git add -A
          git commit -m "Build-${GITHUB_RUN_NUMBER}" \
            -m "Site automatically built in Github Actions"
          git push -f

